name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
        yarn
        yarn build
    - name: Deploy with gh-pages
      env:
        MY_EMAIL: bserre15250@gmail.com
        MY_NAME: benben15
      run: |
        git config --global user.email $MY_EMAIL
        git config --global user.name $MY_NAME
        git remote set-url origin https://$MY_NAME:${{ secrets.GITHUB_TOKEN }}@github.com/BENBEN15/benben15.github.io.git
        yarn deploy
